version: '2'
services:
    knockplop:
        image: michzimny/knockplop
        restart: unless-stopped
        ports:
        - "80:80"
        - "443:443"
        env_file: 
        - env
        volumes:
        - "./certs:/etc/certs:ro"

